# Generated by Django 5.0.1 on 2024-01-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('anounce', models.CharField(max_length=250, verbose_name='Anounce')),
                ('content', models.TextField(verbose_name='Content')),
                ('date_created', models.DateTimeField(verbose_name='Date published')),
            ],
        ),
    ]
