# Generated by Django 5.0.1 on 2024-01-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'News'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='anounce',
            new_name='announce',
        ),
    ]
